services:
  - type: web
    name: speaker-recognition-backend
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    region: singapore
    autoDeploy: true
